### ISSUE TITLE
CI / CD glue

### ISSUE THREAD

**Issue by jackharrisonmohr** [jackharrisonmohr/EDGAR-edge#10]
*GitHub Actions `/.github/workflows/ci.yml`*:

```yaml
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: poetry install --no-interaction
      - run: pytest -q
      - run: make lambda-package
      - run: terraform -chdir=infra fmt -check
  deploy:
    needs: test-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make lambda-package
      - run: terraform -chdir=infra apply -auto-approve
```
